MVCWebApplication/Models/Collections.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCWebApplication.Models
{
    public class Collections
    {
        public static List<Department> departments = new List<Department>()
        {
            new Department { Id = 1, Name = "Arts" },
            new Department { Id = 2, Name = "Commerce" },
            new Department { Id = 3, Name = "Science" }
        };

        public static List<Student> students = new List<Student>()
        {
            new Student { Id = 1, Name = "Anand", Age = 34, DepartmentId = 1 },
            new Student { Id = 2, Name = "Tanuja", Age = 32, DepartmentId = 2 },
            new Student { Id = 3, Name = "Aarya", Age = 16, DepartmentId = 1 },
            new Student { Id = 4, Name = "Mansi", Age = 30, DepartmentId = 3 }
        };
    }
}

MVCWebApplication/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCWebApplication.Models
{
    public class Department
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MVCWebApplication/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCWebApplication.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
    }
}

MVCWebApplication/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCWebApplication.Models
{
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int DepartmentId { get; set; }
    }
}

MVCWebApplication/Controllers/DepartmentController.cs
using MVCWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWebApplication.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult Index()
        {
            return View(Collections.departments);
        }
    }
}

MVCWebApplication/Controllers/EmployeeController.cs
using MVCWebApplication.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCWebApplication.Controllers
{
    public class EmployeeController : Controller
    {
        static List<Employee> employees = new List<Employee>()
        {
            new Employee{ Id = 1, Name = "Anand", Age = 34, Gender = "Male" },
            new Employee{ Id = 2, Name = "Tanuja", Age = 32, Gender = "Female" }
        };

        // GET: Employee
        public ActionResult EmployeesList()
        {
            return View(employees);
        }

        public ActionResult EmployeeDetails(int id)
        {
            Employee employee = employees.Single(Emp => Emp.Id == id);
            return View(employee);
        }

        public ActionResult HyperLinks()
        {
            return View(employees);
        }
    }
}

MVCWebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWebApplication.Controllers
{
    public class HomeController : Controller
    {
        public string Index(string id,string name)
        {
            return "Id = " + id + ", Name = " + name;
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVCWebApplication/Controllers/StudentController.cs
using MVCWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWebApplication.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            List<Student> students = Collections.students.ToList();
            return View(students);
        }

        public ActionResult StudentList(int departmentId)
        {
            List<Student> students = Collections.students.Where(S => S.DepartmentId == departmentId).ToList();
            return View(students);
        }

        public ActionResult Details(int id)
        {
            Student student = Collections.students.First(Student => Student.Id == id);
            return View(student);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Student student)
        {
            Collections.students.Add(student);
            return RedirectToAction("Index");
        }
    }
}

MVCWebApplication/Controllers/TestController.cs
using MVCWebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCWebApplication.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            //ViewBag.Countries = new List<string>()
            //{
            //    "India",
            //    "United States",
            //    "United Kingdom",
            //    "France"
            //};

            ViewData["Countries"] = new List<string>()
            {
                "India",
                "United States",
                "United Kingdom",
                "France"
            };

            return View();
        }
    }
}

MVCWebApplication/Views/Department/Index.cshtml
@model IEnumerable<MVCWebApplication.Models.Department>

@{
    ViewBag.Title = "Departments";
}

<h2>Departments</h2>

<ul>
    @foreach (MVCWebApplication.Models.Department department in Model)
    {
        <li>
            @Html.ActionLink(department.Name, "StudentList", "Student", new { departmentId = department.Id }, null)
        </li>
    }
</ul>

MVCWebApplication/Views/Employee/EmployeeDetails.cshtml
@model MVCWebApplication.Models.Employee

@{
    ViewBag.Title = "EmployeeDetails";
}

<h2>EmployeeDetails</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "EmployeesList") |
    @Html.ActionLink("Hyper Links", "HyperLinks")
</p>

MVCWebApplication/Views/Employee/EmployeesList.cshtml
@model IEnumerable<MVCWebApplication.Models.Employee>

@{
    ViewBag.Title = "EmployeesList";
}

<h2>EmployeesList</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "EmployeeDetails", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVCWebApplication/Views/Employee/HyperLinks.cshtml
@model IEnumerable<MVCWebApplication.Models.Employee>

@{
    ViewBag.Title = "Hyper Links Demo";
}

<h2>Hyper Links Demo</h2>

<ul>
    @foreach (MVCWebApplication.Models.Employee employee in Model)
    {
        <li>
            @Html.ActionLink(employee.Name, "EmployeeDetails", new { id = employee.Id })
        </li>
    }
</ul>

MVCWebApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MVCWebApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MVCWebApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MVCWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCWebApplication/Views/Student/Create.cshtml
@model MVCWebApplication.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepartmentId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepartmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVCWebApplication/Views/Student/Details.cshtml
@model MVCWebApplication.Models.Student

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartmentId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "StudentList", new { departmentId = Model.DepartmentId })
</p>

MVCWebApplication/Views/Student/Index.cshtml
@model IEnumerable<MVCWebApplication.Models.Student>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Age)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepartmentId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DepartmentId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MVCWebApplication/Views/Student/StudentList.cshtml
@model IEnumerable<MVCWebApplication.Models.Student>

@{
    ViewBag.Title = "List Of Students";
}

<h2>List Of Students</h2>

<ul>
    @foreach (MVCWebApplication.Models.Student student in Model)
    {
        <li>
            @Html.ActionLink(student.Name, "Details", new { id = student.Id })
        </li>
    }
</ul>

@Html.ActionLink("Back To Department List", "Index", "Department")

MVCWebApplication/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>List Of Countries</h2>

<ul>
    @*@foreach (var country in ViewBag.Countries)
    {
        <li>@country</li>
    }*@

    @foreach (var country in (List<string>)ViewData["Countries"])
    {
        <li>@country</li>
    }
</ul>